# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueueRPCMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueueRPCMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15QueueRPCMessage.proto\"+\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xe9\x01\n\x17QueueRequestBodyMessage\x12\x10\n\x08\x66ull_url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x1f\n\x07headers\x18\x03 \x03(\x0b\x32\x0e.MapFieldEntry\x12\x36\n\x07\x63ookies\x18\x04 \x03(\x0b\x32%.QueueRequestBodyMessage.CookiesEntry\x12\x12\n\nbody_bytes\x18\x05 \x01(\x0c\x12\x0f\n\x07timeout\x18\x06 \x01(\x05\x1a.\n\x0c\x43ookiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x88\x02\n\x18QueueResponseDataMessage\x12\x10\n\x08is_error\x18\x01 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12\x1f\n\x07headers\x18\x03 \x03(\x0b\x32\x0e.MapFieldEntry\x12\x37\n\x07\x63ookies\x18\x04 \x03(\x0b\x32&.QueueResponseDataMessage.CookiesEntry\x12\x12\n\nbody_bytes\x18\x05 \x01(\x0c\x12\x13\n\x0bworker_name\x18\x06 \x01(\t\x12\x12\n\nworker_mac\x18\x07 \x01(\t\x1a.\n\x0c\x43ookiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)




_MAPFIELDENTRY = _descriptor.Descriptor(
  name='MapFieldEntry',
  full_name='MapFieldEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MapFieldEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MapFieldEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=68,
)


_QUEUEREQUESTBODYMESSAGE_COOKIESENTRY = _descriptor.Descriptor(
  name='CookiesEntry',
  full_name='QueueRequestBodyMessage.CookiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QueueRequestBodyMessage.CookiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='QueueRequestBodyMessage.CookiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=304,
)

_QUEUEREQUESTBODYMESSAGE = _descriptor.Descriptor(
  name='QueueRequestBodyMessage',
  full_name='QueueRequestBodyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_url', full_name='QueueRequestBodyMessage.full_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='method', full_name='QueueRequestBodyMessage.method', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='QueueRequestBodyMessage.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cookies', full_name='QueueRequestBodyMessage.cookies', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_bytes', full_name='QueueRequestBodyMessage.body_bytes', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='QueueRequestBodyMessage.timeout', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUEUEREQUESTBODYMESSAGE_COOKIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=304,
)


_QUEUERESPONSEDATAMESSAGE_COOKIESENTRY = _descriptor.Descriptor(
  name='CookiesEntry',
  full_name='QueueResponseDataMessage.CookiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QueueResponseDataMessage.CookiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='QueueResponseDataMessage.CookiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=304,
)

_QUEUERESPONSEDATAMESSAGE = _descriptor.Descriptor(
  name='QueueResponseDataMessage',
  full_name='QueueResponseDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_error', full_name='QueueResponseDataMessage.is_error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='QueueResponseDataMessage.status_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headers', full_name='QueueResponseDataMessage.headers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cookies', full_name='QueueResponseDataMessage.cookies', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body_bytes', full_name='QueueResponseDataMessage.body_bytes', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_name', full_name='QueueResponseDataMessage.worker_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='worker_mac', full_name='QueueResponseDataMessage.worker_mac', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUEUERESPONSEDATAMESSAGE_COOKIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=571,
)

_QUEUEREQUESTBODYMESSAGE_COOKIESENTRY.containing_type = _QUEUEREQUESTBODYMESSAGE
_QUEUEREQUESTBODYMESSAGE.fields_by_name['headers'].message_type = _MAPFIELDENTRY
_QUEUEREQUESTBODYMESSAGE.fields_by_name['cookies'].message_type = _QUEUEREQUESTBODYMESSAGE_COOKIESENTRY
_QUEUERESPONSEDATAMESSAGE_COOKIESENTRY.containing_type = _QUEUERESPONSEDATAMESSAGE
_QUEUERESPONSEDATAMESSAGE.fields_by_name['headers'].message_type = _MAPFIELDENTRY
_QUEUERESPONSEDATAMESSAGE.fields_by_name['cookies'].message_type = _QUEUERESPONSEDATAMESSAGE_COOKIESENTRY
DESCRIPTOR.message_types_by_name['MapFieldEntry'] = _MAPFIELDENTRY
DESCRIPTOR.message_types_by_name['QueueRequestBodyMessage'] = _QUEUEREQUESTBODYMESSAGE
DESCRIPTOR.message_types_by_name['QueueResponseDataMessage'] = _QUEUERESPONSEDATAMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapFieldEntry = _reflection.GeneratedProtocolMessageType('MapFieldEntry', (_message.Message,), {
  'DESCRIPTOR' : _MAPFIELDENTRY,
  '__module__' : 'QueueRPCMessage_pb2'
  # @@protoc_insertion_point(class_scope:MapFieldEntry)
  })
_sym_db.RegisterMessage(MapFieldEntry)

QueueRequestBodyMessage = _reflection.GeneratedProtocolMessageType('QueueRequestBodyMessage', (_message.Message,), {

  'CookiesEntry' : _reflection.GeneratedProtocolMessageType('CookiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUEUEREQUESTBODYMESSAGE_COOKIESENTRY,
    '__module__' : 'QueueRPCMessage_pb2'
    # @@protoc_insertion_point(class_scope:QueueRequestBodyMessage.CookiesEntry)
    })
  ,
  'DESCRIPTOR' : _QUEUEREQUESTBODYMESSAGE,
  '__module__' : 'QueueRPCMessage_pb2'
  # @@protoc_insertion_point(class_scope:QueueRequestBodyMessage)
  })
_sym_db.RegisterMessage(QueueRequestBodyMessage)
_sym_db.RegisterMessage(QueueRequestBodyMessage.CookiesEntry)

QueueResponseDataMessage = _reflection.GeneratedProtocolMessageType('QueueResponseDataMessage', (_message.Message,), {

  'CookiesEntry' : _reflection.GeneratedProtocolMessageType('CookiesEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUEUERESPONSEDATAMESSAGE_COOKIESENTRY,
    '__module__' : 'QueueRPCMessage_pb2'
    # @@protoc_insertion_point(class_scope:QueueResponseDataMessage.CookiesEntry)
    })
  ,
  'DESCRIPTOR' : _QUEUERESPONSEDATAMESSAGE,
  '__module__' : 'QueueRPCMessage_pb2'
  # @@protoc_insertion_point(class_scope:QueueResponseDataMessage)
  })
_sym_db.RegisterMessage(QueueResponseDataMessage)
_sym_db.RegisterMessage(QueueResponseDataMessage.CookiesEntry)


_QUEUEREQUESTBODYMESSAGE_COOKIESENTRY._options = None
_QUEUERESPONSEDATAMESSAGE_COOKIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
