ACTIVATION_API_KEY = 'FWj8lJIwvbItfw8S5SWGatAqV'


class TransactionStatus:
    CREATED = 'CREATED'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class VNPaySettings:
    VNPAYQR_APP_ID_PROD = "MERCHANT"
    VNPAYQR_CREATE_QR_SECRET_KEY_PROD = "vnpay@Merchant"
    VNPAYQR_CHECK_TRANS_SECRET_KEY_PROD = "vnpay@123"
    VNPAYQR_TERMINAL_ID_PROD = "BEECOST1"
    VNPAYQR_MERCHANT_TYPE_PROD = "4816"
    VNPAYQR_MERCHANT_NAME_PROD = "BEECOST"
    VNPAYQR_MERCHANT_CODE_PROD = "0108677693"
    VNPAYQR_MERCHANT_BEE_HOOK_SECRET_PROD = "BeeCo.st@3004AkRc_Prod6688"

    VNPAYQR_APP_ID = "MERCHANT"
    VNPAYQR_CREATE_QR_SECRET_KEY = "vnpay@MERCHANT"
    VNPAYQR_CHECK_TRANS_SECRET_KEY = "vnpay@123"
    VNPAYQR_TERMINAL_ID = "BEECOST2"
    VNPAYQR_MERCHANT_TYPE = "4816"
    VNPAYQR_MERCHANT_NAME = "BEECOST"
    VNPAYQR_MERCHANT_CODE = "0108677693"
    VNPAYQR_MERCHANT_BEE_HOOK_SECRET = "BeeCo.st@162tRc_Prod6668"


class MomoSettings:
    MOMO_PARTNER_CODE = "MOMOJMVL20230302"
    MOMO_PARTNER_NAME = "METRIC"
    MOMO_REQUEST_TYPE = "captureWallet"
    MOMO_IPN_URL = "https://apiv3.metric.vn/market/momo/payment/hook"
    MOMO_PAYMENT_ENDPOINT = "https://payment.momo.vn/v2/gateway/api/create"
    MOMO_LANG = "vi"
    MOMO_ACCESS_KEY = "VECr9Ntz5mPDPKEb"
    MOMO_SECRET_KEY = "monLkIKStF4Xscg7qowHulz1adV4hX37"


class MomoResponse:
    STATUS_CODE_SUCCESS = 0


class VNPayResponse:
    STATUS_CODE_SUCCESS = "00"
    STATUS_CODE_FAILED = "01"
